### ISSUE TITLE
Chrome DevTools debugging?

### ISSUE THREAD

**Issue by clemsontiger** [edgardleal/require-vuejs#2]
How can I debug the .vue or .html component file for the vue component? the files do not show up in the Sources tree view when using Chrome DevTools. I manually added it, but it doesn't stop on breakpoints.

**Comment by edgardleal** [comment]
You can try use `Ctrl+P` to search by name.
In my tests it works fine on Chrome DevTools.
If after use `Ctrl+P` to search it does not work, please send me a print screen of your DevTools and the version of Chrome.

**Comment by clemsontiger** [comment]
sorry, I'm just not seeing it. attached are screenshots of the networks tab showing my aside.html vue template is being loaded, and another is of the sources tab with the Ctl+P window showing no aside.html found. And then a snippet of my requirejs dependency line where it's pulling in the template aside.html file.
aside.html resides in a components folder under _assets, as you can see, the tree panel doesn't show this folder at all.

thanks.
![sources_tab](https://user-images.githubusercontent.com/6810728/27652401-929bd36e-5c09-11e7-98ee-64382fa39aa1.png)
![network_tab](https://user-images.githubusercontent.com/6810728/27652402-929c7c60-5c09-11e7-99c6-9bfa98fed1d5.png)
![requirejs_line](https://user-images.githubusercontent.com/6810728/27652403-929d0dba-5c09-11e7-83b4-220e905c81d2.png)

**Comment by edgardleal** [comment]
**Notes:**
1 - your `require` line seems to be ok.
2 - What version of this plugin are you using ? 
3 - Are you using npm ? 

This problem was solved in this commit:  https://github.com/edgardleal/require-vuejs/commit/9b740ef6b563af79a3f3a711f6c7ca629dd1490b#diff-4f701644ae12540236790f3ffdb6fad6R72 line 72.
 *The solution consist in after the parser process, include a comment line in top of code telling to browser to register the resulting source to be used in debug.*

If you are not using the last version, please update the plugin , if you are using the last version, let me know and will try to reproduce the error and try to solve this.

**Comment by clemsontiger** [comment]
1. thanks.
2. latest  .min version in the dist folder
3. no

**Comment by edgardleal** [comment]
Ok. I am working in this bug now, and I will tell you when it is solved.

**Comment by edgardleal** [comment]
I found a small bug in my code and I fix it version 1.0.7. Now you can use the file `./dist/require-vuejs.min.js`.

Please let me know if you can debug the code know.

![](http://i.imgur.com/uWJFcTW.png)
![](http://i.imgur.com/0pcWI6Y.png)

**Comment by edgardleal** [comment]
PS: printScreen above is for example code in `./example/` directory on this repository.

**Comment by clemsontiger** [comment]
That did it. works great now. Greatly appreciate you fixing this.
