### ISSUE TITLE
2x times the same class name with modificator in <style>

### ISSUE THREAD

**Issue by kamilmaliszewski** [edgardleal/require-vuejs#28]
Hi ! I found a bug with using a <style> in single file component. Let's check an example:
```
<style>
    .test {
        position: relative;
    }
    .test::after {
        content: '';
    }
</style>
``` 
Using 2x time the same style name (one time normal, 2nd time with modificator) return a following error

> Error: fromText eval for vue!component failed: SyntaxError: missing ) after argument list

Can You check it ?

**Comment by edgardleal** [comment]
This issue was solved in commit e1fc3832408a5533ec777e73d35b64f441e3b719 
You can use any distribution on this folder https://github.com/edgardleal/require-vuejs/tree/develop/dist ( development branch ) or change your code to don't use `''` and try use anything like `""` 

```html
<style>
    .test {
        position: relative;
    }
    .test::after {
        content: "";
    }
</style>
```

If your problem persists, feel free to reopen this issue or create another .
